cmake_minimum_required(VERSION 3.16)
project(stm_lvgl_port_test C)
enable_testing()
add_library(lvgl INTERFACE)
target_include_directories(lvgl INTERFACE ${CMAKE_CURRENT_SOURCE_DIR})
add_subdirectory(.. component)
add_executable(test_port test_lvgl.c)
target_link_libraries(test_port PRIVATE stm_lvgl_port)
add_test(NAME test_port COMMAND test_port)
